// eslint-disable-next-line no-var
var EXERCISE_LIBRARY = [
  // CHEST
  {
    name: 'Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 5,
    defaultRepRangeHigh: 8,
    description: 'Lie flat on a bench and grip the bar just outside shoulder width, pressing it straight up until arms are extended. Lower the bar under control to mid-chest.',
    tips: 'Keep shoulder blades retracted and feet flat on the floor throughout the movement.'
  },
  {
    name: 'Incline Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    muscleGroup: 'upper pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 6,
    defaultRepRangeHigh: 8,
    description: 'Set the bench to 30-45 degrees, grip the bar slightly outside shoulder width, and press up and slightly back. Lower the bar to the upper chest under control.',
    tips: 'A shallower incline targets upper chest more effectively than a steep 60-degree angle.'
  },
  {
    name: 'Decline Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    muscleGroup: 'lower pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 6,
    defaultRepRangeHigh: 10,
    description: 'Set the bench to a slight decline, secure your feet, and press the bar from lower-chest level to full arm extension. Lower slowly back to the chest.',
    tips: 'Decline bench places less stress on the shoulder joint compared to flat or incline.'
  },
  {
    name: 'Dumbbell Bench Press',
    category: 'chest',
    equipment: 'dumbbell',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Lie on a flat bench holding dumbbells at chest level with palms facing forward, then press them up until arms are fully extended. Lower them in a controlled arc back to chest height.',
    tips: 'Allow a slightly wider range of motion than the barbell version for greater chest stretch.'
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'chest',
    equipment: 'dumbbell',
    muscleGroup: 'upper pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Lie on an incline bench set to 30-45 degrees and press the dumbbells from chest level to full extension overhead. Lower the weights slowly, feeling a stretch in the upper chest.',
    tips: 'Maintain a slight elbow tuck to protect the shoulder joint during the lift.'
  },
  {
    name: 'Dumbbell Flye',
    category: 'chest',
    equipment: 'dumbbell',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['anterior deltoid'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Lie flat on a bench holding dumbbells above your chest with a slight bend in the elbows, then lower them out to your sides in a wide arc. Squeeze the chest to bring them back together.',
    tips: 'Think of hugging a large tree — maintain the elbow angle throughout and avoid going too heavy.'
  },
  {
    name: 'Cable Chest Flye',
    category: 'chest',
    equipment: 'cable',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['anterior deltoid'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand in the center of a cable station with handles set at shoulder height, then bring your hands together in front of you in a wide arc. Control the return to maintain constant tension.',
    tips: 'Vary the cable height to target different portions of the pec — high cables hit lower chest, low cables hit upper chest.'
  },
  {
    name: 'Push-Up',
    category: 'chest',
    equipment: 'bodyweight',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid', 'core'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 20,
    description: 'Start in a plank position with hands slightly wider than shoulder width, then lower your chest to just above the floor by bending your elbows. Press back up to the starting position.',
    tips: 'Keep your body in a straight line from head to heels and avoid letting hips sag or pike up.'
  },
  {
    name: 'Chest Dip',
    category: 'chest',
    equipment: 'bodyweight',
    muscleGroup: 'lower pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Support yourself on parallel bars, lean forward slightly, then lower yourself by bending your elbows until you feel a stretch in your chest. Push back up to full arm extension.',
    tips: 'Lean forward to shift emphasis to the chest; staying upright shifts the focus more to the triceps.'
  },
  {
    name: 'Machine Chest Press',
    category: 'chest',
    equipment: 'machine',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['triceps', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Sit in the chest press machine with the handles at chest level, then press forward until arms are fully extended. Return the handles slowly to the starting position.',
    tips: 'Machines are great for beginners or for high-rep burnout sets since stabilizers are less involved.'
  },
  {
    name: 'Pec Deck',
    category: 'chest',
    equipment: 'machine',
    muscleGroup: 'pectoralis major',
    secondaryMuscles: ['anterior deltoid'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Sit in the pec deck machine with your forearms resting on the pads, then squeeze your chest to bring the pads together in front of you. Slowly return to the start with a full stretch.',
    tips: 'Focus on the squeeze at the peak contraction and avoid letting the weight stack slam back down.'
  },
  // BACK
  {
    name: 'Barbell Deadlift',
    category: 'back',
    equipment: 'barbell',
    muscleGroup: 'erector spinae',
    secondaryMuscles: ['glutes', 'hamstrings', 'trapezius', 'lats'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 3,
    defaultRepRangeHigh: 6,
    description: 'Stand over the bar with it over mid-foot, hinge at the hips to grip it, then drive through the floor extending your hips and knees simultaneously to stand up straight. Lower the bar back to the floor with a controlled hip hinge.',
    tips: 'Keep the bar in contact with your legs throughout the pull and maintain a neutral spine.'
  },
  {
    name: 'Barbell Row',
    category: 'back',
    equipment: 'barbell',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['rhomboids', 'rear deltoid', 'biceps'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 6,
    defaultRepRangeHigh: 8,
    description: 'Hinge forward until your torso is roughly parallel to the floor, grip the bar shoulder-width apart, and row it toward your lower abdomen by driving your elbows back. Lower the bar under control.',
    tips: 'Avoid using excessive body English — a slight hip drive is acceptable but the back muscles should do the work.'
  },
  {
    name: 'Pull-Up',
    category: 'back',
    equipment: 'bodyweight',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['biceps', 'rear deltoid', 'rhomboids'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 5,
    defaultRepRangeHigh: 8,
    description: 'Hang from a bar with a shoulder-width overhand grip, then pull yourself up until your chin clears the bar by retracting your shoulder blades and driving your elbows down. Lower yourself slowly to a full hang.',
    tips: 'Think about pulling your elbows to your hips rather than just bending your arms.'
  },
  {
    name: 'Chin-Up',
    category: 'back',
    equipment: 'bodyweight',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['biceps', 'rear deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 6,
    defaultRepRangeHigh: 10,
    description: 'Hang from a bar with a shoulder-width underhand grip, then pull yourself up until your chin clears the bar. Lower yourself under control to a full hang.',
    tips: 'The supinated grip involves the biceps more than the overhand pull-up grip.'
  },
  {
    name: 'Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['biceps', 'rear deltoid', 'rhomboids'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Sit at the pulldown station with thighs secured under the pad, grip the bar wide, and pull it down to your upper chest by driving your elbows toward your hips. Slowly return the bar to the starting position.',
    tips: 'Lean back slightly and drive the elbows straight down to maximize lat engagement.'
  },
  {
    name: 'Seated Cable Row',
    category: 'back',
    equipment: 'cable',
    muscleGroup: 'rhomboids',
    secondaryMuscles: ['latissimus dorsi', 'biceps', 'rear deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Sit at the cable row station with feet on the platform, hold the V-bar attachment, and row it toward your lower abdomen by squeezing your shoulder blades together. Extend arms fully between reps for a full lat stretch.',
    tips: 'Maintain a tall spine and avoid rounding the lower back by leaning excessively forward.'
  },
  {
    name: 'Dumbbell Single-Arm Row',
    category: 'back',
    equipment: 'dumbbell',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['rhomboids', 'rear deltoid', 'biceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Place one knee and hand on a bench for support, hold a dumbbell in the opposite hand, and row it toward your hip by driving the elbow back and up. Lower the weight slowly to a full arm extension.',
    tips: 'Allow the shoulder to dip at the bottom to increase the range of motion and lat stretch.'
  },
  {
    name: 'T-Bar Row',
    category: 'back',
    equipment: 'barbell',
    muscleGroup: 'rhomboids',
    secondaryMuscles: ['latissimus dorsi', 'biceps', 'rear deltoid'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 6,
    defaultRepRangeHigh: 10,
    description: 'Straddle the T-bar landmine or use a T-bar row machine, grip the handle, and row the weight toward your chest while keeping your torso parallel to the floor. Lower the weight slowly.',
    tips: 'Use a neutral grip attachment to allow the elbows to travel close to the body for better lat activation.'
  },
  {
    name: 'Straight-Arm Pulldown',
    category: 'back',
    equipment: 'cable',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['triceps long head'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand facing a high pulley cable with a straight bar attachment, keep your arms straight with a slight elbow bend, and pull the bar down to your thighs using only your lats. Return slowly to the overhead position.',
    tips: 'This is an excellent isolation movement for the lats and a great way to feel the lat-to-hip connection.'
  },
  {
    name: 'Face Pull',
    category: 'shoulders',
    equipment: 'cable',
    muscleGroup: 'rear deltoid',
    secondaryMuscles: ['rotator cuff', 'rhomboids', 'trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Set a rope attachment at upper chest height, grip the rope with thumbs pointing backward, and pull it toward your face while flaring your elbows out. Pause at the end position with your upper arms parallel to the floor.',
    tips: 'This exercise is critical for shoulder health — prioritize it in every upper-body session.'
  },
  {
    name: 'Hyperextension',
    category: 'back',
    equipment: 'bodyweight',
    muscleGroup: 'erector spinae',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Secure your feet in the hyperextension bench, hinge at the hips to lower your torso toward the floor, then squeeze your glutes and lower back to raise your torso until it is parallel to the floor.',
    tips: 'Avoid hyperextending the lower back beyond parallel — hold a weight plate for added resistance.'
  },
  // SHOULDERS
  {
    name: 'Barbell Overhead Press',
    category: 'shoulders',
    equipment: 'barbell',
    muscleGroup: 'anterior deltoid',
    secondaryMuscles: ['lateral deltoid', 'triceps', 'upper trapezius'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 5,
    defaultRepRangeHigh: 8,
    description: 'Stand with the bar at collarbone height, grip just outside shoulder width, and press it straight overhead until arms are locked out. Lower the bar back to the starting position under control.',
    tips: 'Tuck your chin slightly as the bar passes your face and push your head through once the bar clears.'
  },
  {
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    muscleGroup: 'anterior deltoid',
    secondaryMuscles: ['lateral deltoid', 'triceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Sit on an upright bench holding dumbbells at shoulder height with palms facing forward, then press them straight overhead until arms are extended. Lower them back to shoulder height.',
    tips: 'A neutral grip (palms facing each other) is a shoulder-friendly variation if you experience anterior shoulder discomfort.'
  },
  {
    name: 'Dumbbell Lateral Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    muscleGroup: 'lateral deltoid',
    secondaryMuscles: ['upper trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand holding dumbbells at your sides, then raise them out to the sides until your arms are parallel to the floor with thumbs slightly lower than pinkies. Lower them slowly back to your sides.',
    tips: 'Lean slightly forward and lead with the elbow, not the wrist, to better isolate the lateral head of the deltoid.'
  },
  {
    name: 'Cable Lateral Raise',
    category: 'shoulders',
    equipment: 'cable',
    muscleGroup: 'lateral deltoid',
    secondaryMuscles: ['upper trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand sideways to a low cable pulley, grip the handle with the far hand, and raise it out to the side until your arm is parallel to the floor. Lower it under control.',
    tips: 'Cables provide constant tension throughout the movement, unlike dumbbells which have less tension at the bottom.'
  },
  {
    name: 'Dumbbell Front Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    muscleGroup: 'anterior deltoid',
    secondaryMuscles: ['upper trapezius', 'pectoralis minor'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Stand holding dumbbells in front of your thighs with palms facing down, then raise one or both arms forward to shoulder height. Lower them slowly back to the starting position.',
    tips: 'Use lighter weight and controlled reps — most people already get significant anterior delt work from pressing exercises.'
  },
  {
    name: 'Rear Delt Dumbbell Flye',
    category: 'shoulders',
    equipment: 'dumbbell',
    muscleGroup: 'rear deltoid',
    secondaryMuscles: ['rhomboids', 'trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Hinge forward at the hips until your torso is nearly parallel to the floor, hold dumbbells hanging below your chest, and raise them out to the sides by squeezing your rear delts. Lower them slowly.',
    tips: 'Keep a slight bend in the elbows and avoid shrugging the traps — focus on squeezing the rear delt.'
  },
  {
    name: 'Arnold Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    muscleGroup: 'anterior deltoid',
    secondaryMuscles: ['lateral deltoid', 'triceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Start with dumbbells at chin height with palms facing you, then press overhead while rotating your palms forward, finishing with palms facing away. Reverse the motion on the way back down.',
    tips: 'The rotation targets all three deltoid heads and adds variety to standard shoulder pressing.'
  },
  {
    name: 'Machine Shoulder Press',
    category: 'shoulders',
    equipment: 'machine',
    muscleGroup: 'anterior deltoid',
    secondaryMuscles: ['lateral deltoid', 'triceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Sit in the shoulder press machine with handles at ear height, then press them upward until arms are fully extended. Lower the handles back to the starting position.',
    tips: 'Machines allow you to push close to failure more safely without worrying about balancing the weight.'
  },
  {
    name: 'Upright Row',
    category: 'shoulders',
    equipment: 'barbell',
    muscleGroup: 'lateral deltoid',
    secondaryMuscles: ['upper trapezius', 'biceps'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Hold a barbell with a shoulder-width overhand grip in front of your thighs, then pull it straight up toward your chin by leading with the elbows. Lower the bar slowly back to the starting position.',
    tips: 'Use a wider grip to reduce internal shoulder rotation and minimize impingement risk.'
  },
  // LEGS
  {
    name: 'Barbell Back Squat',
    category: 'legs',
    equipment: 'barbell',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'erector spinae'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 5,
    defaultRepRangeHigh: 8,
    description: 'Place the barbell across your upper traps, brace your core, and squat down by pushing your knees out and hips back until thighs are at least parallel to the floor. Drive through your heels to stand back up.',
    tips: 'Ensure your knees track over your toes and maintain a neutral spine throughout the movement.'
  },
  {
    name: 'Front Squat',
    category: 'legs',
    equipment: 'barbell',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'upper back', 'core'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 4,
    defaultRepRangeHigh: 6,
    description: 'Rest the barbell on your front deltoids with elbows high and fingers under the bar, then squat down keeping your torso upright. Drive through your heels to stand.',
    tips: 'A more upright torso position shifts emphasis to the quads and is easier on the lower back than back squats.'
  },
  {
    name: 'Leg Press',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Sit in the leg press machine with feet hip-width apart on the platform, release the safeties, and lower the platform toward your chest. Press back to near full extension without locking the knees.',
    tips: 'A higher foot position emphasizes glutes and hamstrings; a lower position emphasizes quads.'
  },
  {
    name: 'Romanian Deadlift',
    category: 'legs',
    equipment: 'barbell',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'erector spinae'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 10,
    description: 'Hold a barbell at hip height with a shoulder-width grip, push your hips back while lowering the bar along your thighs until you feel a deep hamstring stretch. Drive your hips forward to return to the starting position.',
    tips: 'Maintain a neutral spine and a slight knee bend — do not let the lower back round at the bottom.'
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    category: 'legs',
    equipment: 'dumbbell',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'erector spinae'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Hold dumbbells in front of your thighs, hinge at the hips while keeping your back straight, and lower the dumbbells along your legs until you feel a stretch in your hamstrings. Drive hips forward to return.',
    tips: 'Dumbbells allow a greater range of motion and help identify and correct left-right imbalances.'
  },
  {
    name: 'Leg Curl',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['gastrocnemius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Lie face down on the leg curl machine with the pad just above your heels, then curl your legs up toward your glutes by contracting your hamstrings. Lower the weight slowly to full extension.',
    tips: 'Plantar flex your feet (point toes) during the curl to activate the gastrocnemius as well.'
  },
  {
    name: 'Leg Extension',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'quadriceps',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Sit in the leg extension machine with the pad on the front of your ankles, then extend your legs until they are straight by contracting your quads. Lower the weight slowly back to 90 degrees.',
    tips: 'Pause briefly at the top of each rep for an extra quad squeeze, and avoid using momentum.'
  },
  {
    name: 'Walking Lunge',
    category: 'legs',
    equipment: 'dumbbell',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Hold dumbbells at your sides and step forward into a lunge, lowering your back knee toward the floor. Drive through the front heel to step forward into the next lunge.',
    tips: 'Keep your torso upright and your front knee tracking over your second toe throughout each rep.'
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'legs',
    equipment: 'dumbbell',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 10,
    description: 'Place your rear foot on a bench and hold dumbbells at your sides, then lower your back knee toward the floor by bending the front leg. Drive through the front heel to return to standing.',
    tips: 'Place the front foot far enough from the bench that the shin is roughly vertical at the bottom of the rep.'
  },
  {
    name: 'Calf Raise',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'gastrocnemius',
    secondaryMuscles: ['soleus'],
    isCompound: false,
    defaultSets: 4,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 20,
    description: 'Stand on the calf raise platform with the balls of your feet on the edge and lower your heels below the platform for a full stretch. Rise up onto your toes and pause at the top before lowering.',
    tips: 'Calves respond well to high volume — include a full stretch at the bottom of each rep.'
  },
  {
    name: 'Seated Calf Raise',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'soleus',
    secondaryMuscles: ['gastrocnemius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Sit in the seated calf raise machine with the pad on your lower thighs, place the balls of your feet on the platform, and raise your heels as high as possible. Lower slowly for a full stretch.',
    tips: 'The seated position bends the knee, which takes the gastrocnemius out of the movement and targets the soleus more directly.'
  },
  {
    name: 'Hip Abductor Machine',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'gluteus medius',
    secondaryMuscles: ['tensor fasciae latae'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Sit in the hip abductor machine with pads on the outside of your knees, then push your legs apart against the resistance. Return slowly to the starting position.',
    tips: 'Lean slightly forward to better activate the glute medius rather than the TFL.'
  },
  {
    name: 'Hip Adductor Machine',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'hip adductors',
    secondaryMuscles: ['gracilis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Sit in the hip adductor machine with pads on the inside of your knees and legs spread apart, then squeeze your legs together against the resistance. Return slowly to the spread position.',
    tips: 'Use a full range of motion and control the eccentric to build inner thigh strength and reduce injury risk.'
  },
  {
    name: 'Goblet Squat',
    category: 'legs',
    equipment: 'dumbbell',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Hold a dumbbell vertically at your chest with both hands, squat down until your elbows touch your inner thighs, then drive through your heels to stand. Keep your chest tall and knees tracking outward.',
    tips: 'Excellent squat teaching tool — the front load naturally encourages an upright torso position.'
  },
  {
    name: 'Glute Bridge',
    category: 'legs',
    equipment: 'bodyweight',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'erector spinae'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Lie on your back with knees bent and feet flat on the floor, then drive your hips up by squeezing your glutes until your body forms a straight line from knees to shoulders. Lower your hips back down.',
    tips: 'Add a barbell across the hips for a barbell hip thrust variation — one of the best glute exercises available.'
  },
  {
    name: 'Hip Thrust',
    category: 'legs',
    equipment: 'barbell',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'quadriceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Sit on the floor with your upper back against a bench and a barbell across your hips, then drive your hips up by squeezing your glutes until your body is parallel to the floor. Lower with control.',
    tips: 'Keep your chin tucked and core braced to avoid excessive lower back arch at the top.'
  },
  // ARMS
  {
    name: 'Barbell Curl',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis', 'brachioradialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Stand holding a barbell with a shoulder-width underhand grip, then curl the bar toward your shoulders by flexing your elbows. Lower it slowly back to the starting position.',
    tips: 'Keep your elbows pinned to your sides and avoid using your back to swing the weight up.'
  },
  {
    name: 'Dumbbell Curl',
    category: 'arms',
    equipment: 'dumbbell',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis', 'brachioradialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Stand holding dumbbells at your sides with palms forward, then curl them toward your shoulders by flexing your elbows. Supinate (rotate) the wrist at the top for a stronger bicep contraction.',
    tips: 'Alternate arms or curl both simultaneously — both are effective. Control the eccentric for maximum growth stimulus.'
  },
  {
    name: 'Hammer Curl',
    category: 'arms',
    equipment: 'dumbbell',
    muscleGroup: 'brachialis',
    secondaryMuscles: ['biceps brachii', 'brachioradialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Stand holding dumbbells with a neutral grip (palms facing each other) and curl them toward your shoulders without rotating the wrists. Lower them slowly back to your sides.',
    tips: 'Hammer curls target the brachialis and brachioradialis more than supinated curls, adding arm thickness.'
  },
  {
    name: 'Preacher Curl',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Place your upper arms flat on the preacher bench pad and grip the barbell with an underhand hold, then curl the bar toward your face. Lower it slowly until your arms are nearly fully extended.',
    tips: 'The preacher bench removes the ability to cheat and places maximum tension on the bicep at the stretched position.'
  },
  {
    name: 'Cable Curl',
    category: 'arms',
    equipment: 'cable',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand facing a low cable pulley with a straight bar or EZ bar attachment, and curl the handle toward your shoulders. Lower it under control, maintaining constant tension throughout.',
    tips: 'Cables provide constant tension at the bottom of the movement where free weights have less.'
  },
  {
    name: 'Incline Dumbbell Curl',
    category: 'arms',
    equipment: 'dumbbell',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Sit on an incline bench set to 45-60 degrees with arms hanging straight down, then curl the dumbbells toward your shoulders. The incline position pre-stretches the long head of the bicep.',
    tips: 'The stretch position on an incline maximally lengthens the bicep, which research suggests improves hypertrophy.'
  },
  {
    name: 'Tricep Pushdown',
    category: 'arms',
    equipment: 'cable',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Stand facing a high cable pulley with a straight bar or rope attachment, grip it with your elbows at your sides, and push down until your arms are fully extended. Return to 90 degrees with control.',
    tips: 'Lean slightly forward and keep your elbows pinned to your sides for maximum tricep isolation.'
  },
  {
    name: 'Overhead Tricep Extension',
    category: 'arms',
    equipment: 'dumbbell',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Hold a single dumbbell overhead with both hands gripping the top plate, lower it behind your head by bending your elbows, then press back up to full extension. Keep your elbows pointing straight up.',
    tips: 'The overhead position stretches the long head of the tricep maximally, making it excellent for long head hypertrophy.'
  },
  {
    name: 'Skull Crusher',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Lie on a flat bench holding an EZ bar or barbell above your chest with a narrow grip, then lower it toward your forehead by bending only your elbows. Press back to the starting position.',
    tips: 'Allow a slight backward angle rather than straight down to reduce elbow stress and increase range of motion.'
  },
  {
    name: 'Tricep Dip',
    category: 'arms',
    equipment: 'bodyweight',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: ['anterior deltoid', 'pectoralis major'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 15,
    description: 'Support yourself on parallel bars with arms extended, then lower yourself by bending your elbows while keeping your torso upright. Press back to full extension.',
    tips: 'Stay upright to target triceps; leaning forward shifts work to the chest. Add weight with a dip belt for progression.'
  },
  {
    name: 'Close-Grip Bench Press',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: ['pectoralis major', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 10,
    description: 'Lie on a bench and grip the bar with hands shoulder-width apart or slightly narrower, then press it off the rack and lower it to the lower chest. Press back up by driving your elbows forward.',
    tips: 'Do not take too narrow a grip as it strains the wrists — shoulder width is narrow enough for maximal tricep activation.'
  },
  {
    name: 'Rope Tricep Pushdown',
    category: 'arms',
    equipment: 'cable',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Attach a rope to a high cable pulley, grip each end with palms facing each other, and push down while spreading the rope apart at the bottom. Return to 90 degrees with control.',
    tips: 'Spreading the rope at the bottom of each rep increases the range of motion and enhances the tricep contraction.'
  },
  {
    name: 'Wrist Curl',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'wrist flexors',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Sit with your forearms resting on a bench with wrists hanging off the edge, grip a barbell with an underhand hold, and curl your wrists upward. Lower slowly back to the start.',
    tips: 'Use light weight and high reps — the forearm flexors are small muscles prone to overuse injury.'
  },
  // CORE
  {
    name: 'Plank',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['transverse abdominis', 'obliques', 'glutes'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 30,
    defaultRepRangeHigh: 60,
    description: 'Hold a push-up position with your forearms on the floor, keeping your body in a perfectly straight line from head to heels. Brace your core as if bracing for a punch.',
    tips: 'Duration is measured in seconds — aim to progress by adding time each week. Quality over duration.'
  },
  {
    name: 'Crunch',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Lie on your back with knees bent and hands behind your head, then curl your upper body toward your knees using only your abs. Lower back to the starting position with control.',
    tips: 'Do not pull on your neck — simply rest your fingers behind your head and let your abs do the work.'
  },
  {
    name: 'Hanging Leg Raise',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['hip flexors', 'obliques'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Hang from a pull-up bar with arms extended, then raise your legs until they are parallel to the floor (or higher for advanced) by flexing your hip flexors and rounding your lower back. Lower them slowly.',
    tips: 'Posterior pelvic tilt at the top of the movement ensures the abs are contracting maximally rather than just the hip flexors.'
  },
  {
    name: 'Ab Wheel Rollout',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['transverse abdominis', 'lats'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Kneel on the floor gripping the ab wheel, then roll it forward while keeping your core braced and your back flat until your body is nearly parallel to the floor. Contract your abs to pull the wheel back.',
    tips: 'Start with a partial range of motion and progress gradually — full rollouts are very demanding on the lumbar spine.'
  },
  {
    name: 'Russian Twist',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'obliques',
    secondaryMuscles: ['rectus abdominis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 20,
    defaultRepRangeHigh: 30,
    description: 'Sit on the floor with knees bent and feet raised, lean back slightly, and rotate your torso from side to side while holding your hands or a weight plate together.',
    tips: 'Count each side-to-side rotation as one rep — add a weight plate to increase resistance.'
  },
  {
    name: 'Cable Crunch',
    category: 'core',
    equipment: 'cable',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['obliques'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Kneel facing a high cable pulley with a rope attachment, grip the rope beside your face, then crunch your elbows toward your knees by contracting your abs. Return to the starting position under control.',
    tips: 'Unlike many ab exercises, cable crunches can be progressively loaded, making them excellent for ab hypertrophy.'
  },
  {
    name: 'Side Plank',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'obliques',
    secondaryMuscles: ['transverse abdominis', 'gluteus medius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 20,
    defaultRepRangeHigh: 45,
    description: 'Lie on your side and prop yourself up on one forearm with your body in a straight line, then hold this position by contracting your obliques and core. Switch sides.',
    tips: 'Stack your feet or stagger them for balance — keep your hips from sagging toward the floor.'
  },
  {
    name: 'Dead Bug',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'transverse abdominis',
    secondaryMuscles: ['rectus abdominis', 'hip flexors'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Lie on your back with arms pointed to the ceiling and knees bent at 90 degrees, then slowly lower one arm and the opposite leg toward the floor while pressing your lower back into the floor. Return and alternate sides.',
    tips: 'Move slowly and focus on keeping your lower back pressed firmly against the floor throughout every rep.'
  },
  {
    name: 'Pallof Press',
    category: 'core',
    equipment: 'cable',
    muscleGroup: 'transverse abdominis',
    secondaryMuscles: ['obliques'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Stand sideways to a cable machine at about chest height, hold the handle at your sternum with both hands, then press it straight out and bring it back while resisting rotation. Switch sides.',
    tips: 'The Pallof press is an anti-rotation exercise — the goal is to prevent your body from rotating, not to rotate it.'
  },
  {
    name: 'Reverse Crunch',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['hip flexors'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Lie on your back with knees bent at 90 degrees and hands beside your hips, then draw your knees toward your chest by posteriorly tilting your pelvis. Lower your feet back to just above the floor.',
    tips: 'Focus on the pelvic tilt at the top of the movement to maximize lower ab engagement.'
  },
  // ADDITIONAL EXERCISES - BACK
  {
    name: 'Rack Pull',
    category: 'back',
    equipment: 'barbell',
    muscleGroup: 'erector spinae',
    secondaryMuscles: ['trapezius', 'glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 4,
    defaultRepRangeHigh: 6,
    description: 'Set the bar in a power rack at just below knee height and perform a deadlift from this elevated starting position. Extend your hips and knees to stand fully erect.',
    tips: 'Rack pulls allow heavier loading than full deadlifts and are excellent for building upper back and trap strength.'
  },
  {
    name: 'Chest-Supported Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    muscleGroup: 'rhomboids',
    secondaryMuscles: ['latissimus dorsi', 'rear deltoid', 'biceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Lie face down on an incline bench set to 30-45 degrees, hold a dumbbell in each hand, and row them toward your hips by squeezing your shoulder blades together. Lower with control.',
    tips: 'The chest support eliminates lower back strain and body English, ensuring the back muscles do all the work.'
  },
  {
    name: 'Band Pull-Apart',
    category: 'back',
    equipment: 'band',
    muscleGroup: 'rear deltoid',
    secondaryMuscles: ['rhomboids', 'trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Hold a resistance band in front of you at shoulder height with arms extended, then pull it apart by spreading your arms horizontally until the band touches your chest. Return with control.',
    tips: 'Great as a warm-up or superset exercise — use a lighter band to maintain strict form throughout.'
  },
  // ADDITIONAL CHEST
  {
    name: 'Landmine Press',
    category: 'chest',
    equipment: 'barbell',
    muscleGroup: 'upper pectoralis major',
    secondaryMuscles: ['anterior deltoid', 'triceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Stand over the anchored end of a landmine barbell, hold the sleeve with both hands at shoulder height, and press it upward and forward until your arms are extended. Lower with control.',
    tips: 'The angled press path is shoulder-friendly and excellent for targeting the upper chest without needing an incline bench.'
  },
  // ADDITIONAL SHOULDERS
  {
    name: 'Cable Front Raise',
    category: 'shoulders',
    equipment: 'cable',
    muscleGroup: 'anterior deltoid',
    secondaryMuscles: ['upper trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand facing away from a low cable pulley, grip the handle behind you, and raise your arm forward and upward to shoulder height. Lower it back slowly.',
    tips: 'Cables provide smooth, constant tension throughout the range of motion compared to dumbbells.'
  },
  {
    name: 'Dumbbell Shrug',
    category: 'shoulders',
    equipment: 'dumbbell',
    muscleGroup: 'upper trapezius',
    secondaryMuscles: ['levator scapulae'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand holding dumbbells at your sides and shrug your shoulders straight up toward your ears as high as possible. Pause briefly at the top and lower them slowly.',
    tips: 'Avoid rolling the shoulders forward — straight up and down is the safest path for trap development.'
  },
  {
    name: 'Barbell Shrug',
    category: 'shoulders',
    equipment: 'barbell',
    muscleGroup: 'upper trapezius',
    secondaryMuscles: ['levator scapulae'],
    isCompound: false,
    defaultSets: 4,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Stand holding a barbell in front of your thighs with an overhand grip, then shrug your shoulders directly upward as high as possible. Lower them slowly back to the starting position.',
    tips: 'Use straps if grip strength is limiting the amount of weight you can lift.'
  },
  // ADDITIONAL LEGS
  {
    name: 'Sumo Deadlift',
    category: 'legs',
    equipment: 'barbell',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'quadriceps', 'adductors', 'erector spinae'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 4,
    defaultRepRangeHigh: 6,
    description: 'Stand with feet wider than hip-width and toes pointed outward, grip the bar inside your legs, and drive through the floor extending hips and knees. Maintain a more upright torso than a conventional deadlift.',
    tips: 'Sumo deadlift shortens the range of motion and places more emphasis on the hips and inner thighs.'
  },
  {
    name: 'Step-Up',
    category: 'legs',
    equipment: 'dumbbell',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Hold dumbbells at your sides, step one foot onto a box or bench, and drive through that heel to bring your other foot up. Step back down and repeat on the same leg or alternate.',
    tips: 'Use a box height where your thigh is at or below parallel when the foot is on the step.'
  },
  {
    name: 'Nordic Hamstring Curl',
    category: 'legs',
    equipment: 'bodyweight',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 5,
    defaultRepRangeHigh: 8,
    description: 'Kneel on a padded surface with your ankles secured, then lower your body toward the floor as slowly as possible by straightening your knees. Use your hands to catch yourself and spring back up.',
    tips: 'One of the most effective hamstring exercises for injury prevention — start with negatives only and progress slowly.'
  },
  {
    name: 'Standing Band Kickback',
    category: 'legs',
    equipment: 'band',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Attach a band around your ankle and a fixed point low to the ground, then kick the banded leg backward while squeezing the glute. Return to the starting position under control.',
    tips: 'Keep the torso still and the movement isolated to the hip — avoid arching the lower back excessively.'
  },
  // ADDITIONAL ARMS
  {
    name: 'Concentration Curl',
    category: 'arms',
    equipment: 'dumbbell',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Sit on a bench, brace your elbow against the inside of your thigh, and curl the dumbbell upward toward your shoulder. Lower it slowly back to full extension.',
    tips: 'The braced elbow position eliminates momentum and puts maximum tension on the bicep at the peak contraction.'
  },
  {
    name: 'EZ Bar Curl',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'biceps brachii',
    secondaryMuscles: ['brachialis', 'brachioradialis'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Stand holding an EZ curl bar with a shoulder-width underhand grip at the angled portions, then curl it toward your shoulders. Lower it back slowly to the starting position.',
    tips: 'The EZ bar reduces wrist and elbow strain compared to a straight barbell while still effectively targeting the biceps.'
  },
  {
    name: 'Reverse Curl',
    category: 'arms',
    equipment: 'barbell',
    muscleGroup: 'brachioradialis',
    secondaryMuscles: ['brachialis', 'biceps brachii'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Hold a barbell with an overhand (pronated) grip at shoulder width, then curl it toward your shoulders while keeping your elbows at your sides. Lower it slowly back.',
    tips: 'Use lighter weight than regular curls — the reverse grip puts the biceps at a mechanical disadvantage.'
  },
  {
    name: 'Overhead Cable Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: [],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Face away from a high cable pulley, grip the rope overhead, and extend your arms forward until they are straight. Return to 90 degrees with control.',
    tips: 'The overhead position maximally stretches the long head of the tricep for greater muscle activation.'
  },
  {
    name: 'Diamond Push-Up',
    category: 'arms',
    equipment: 'bodyweight',
    muscleGroup: 'triceps brachii',
    secondaryMuscles: ['pectoralis major', 'anterior deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Place your hands close together beneath your chest forming a diamond shape with your thumbs and index fingers, then perform a push-up. Lower your chest to your hands and press back up.',
    tips: 'Keep your elbows close to your body and pointed backward to maximize tricep engagement.'
  },
  // ADDITIONAL CORE
  {
    name: 'Bicycle Crunch',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'obliques',
    secondaryMuscles: ['rectus abdominis', 'hip flexors'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 20,
    defaultRepRangeHigh: 30,
    description: 'Lie on your back with hands behind your head, bring one knee toward your chest while rotating the opposite elbow toward it, then switch sides in a cycling motion.',
    tips: 'Perform slowly and deliberately — rapid cycling is cheating and reduces oblique activation.'
  },
  {
    name: 'V-Up',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['hip flexors'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Lie flat on your back with arms extended overhead, then simultaneously raise your legs and torso to meet at the top, forming a V shape. Lower both back to the floor with control.',
    tips: 'Keep your legs straight and reach your hands toward your feet at the top for maximum contraction.'
  },
  {
    name: 'Mountain Climber',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'transverse abdominis',
    secondaryMuscles: ['rectus abdominis', 'hip flexors', 'obliques'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 20,
    defaultRepRangeHigh: 30,
    description: 'Start in a push-up position, then drive one knee toward your chest and immediately switch legs in an alternating running motion while keeping your hips level. Maintain a strong plank position throughout.',
    tips: 'Keep your hips level and avoid letting them pike up — the core should be the primary mover, not the hip flexors.'
  },
  {
    name: 'Weighted Sit-Up',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'rectus abdominis',
    secondaryMuscles: ['hip flexors'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Lie on your back with knees bent, hold a weight plate at your chest or extended overhead, then sit all the way up. Lower yourself slowly back to the floor.',
    tips: 'Adding a weight plate transforms the sit-up from a bodyweight movement into a progressively loadable exercise.'
  },
  {
    name: 'Hollow Body Hold',
    category: 'core',
    equipment: 'bodyweight',
    muscleGroup: 'transverse abdominis',
    secondaryMuscles: ['rectus abdominis', 'hip flexors'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 20,
    defaultRepRangeHigh: 45,
    description: 'Lie on your back, press your lower back into the floor, extend your arms overhead, and raise your legs a few inches off the ground. Hold this position while breathing steadily.',
    tips: 'Press your lower back firmly into the floor throughout — if you cannot maintain this, raise your legs higher.'
  },
  // ADDITIONAL LEGS
  {
    name: 'Seated Leg Curl',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['gastrocnemius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Sit in the seated leg curl machine with the shin pad above your heels, then curl your feet downward and back toward your glutes. Control the return to full extension.',
    tips: 'The seated position provides a more complete stretch of the hamstring compared to the lying version.'
  },
  {
    name: 'Hack Squat',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 4,
    defaultRepRangeLow: 8,
    defaultRepRangeHigh: 12,
    description: 'Position yourself in the hack squat machine with shoulders under the pads and feet on the platform, then lower down until thighs are parallel. Drive through your heels to push the platform back up.',
    tips: 'Place feet lower on the platform to emphasize quads; higher foot placement involves more glutes and hamstrings.'
  },
  {
    name: 'Donkey Calf Raise',
    category: 'legs',
    equipment: 'machine',
    muscleGroup: 'gastrocnemius',
    secondaryMuscles: ['soleus'],
    isCompound: false,
    defaultSets: 4,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 20,
    description: 'Position yourself in the donkey calf raise machine with your lower back pad in place, then raise up on your toes as high as possible. Lower your heels below the platform for a full stretch.',
    tips: 'The hip-flexed position of donkey calf raises provides a greater gastrocnemius stretch than standing raises.'
  },
  {
    name: 'Resistance Band Squat',
    category: 'legs',
    equipment: 'band',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 15,
    defaultRepRangeHigh: 20,
    description: 'Stand on a resistance band with feet shoulder-width apart, bring the band up to your shoulders, and perform a squat. Lower until thighs are parallel and drive back up.',
    tips: 'Resistance bands are ideal for traveling or home workouts when barbells are not available.'
  },
  {
    name: 'Cable Pull-Through',
    category: 'legs',
    equipment: 'cable',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'erector spinae'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 12,
    defaultRepRangeHigh: 15,
    description: 'Stand facing away from a low cable pulley, grip the rope between your legs, hinge forward at the hips allowing the cable to pull your hands back, then drive your hips forward to stand. Squeeze the glutes at the top.',
    tips: 'This is a hip hinge pattern similar to the deadlift and teaches proper glute engagement for beginners.'
  },
  // ADDITIONAL SHOULDERS/BACK
  {
    name: 'Landmine Lateral Raise',
    category: 'shoulders',
    equipment: 'barbell',
    muscleGroup: 'lateral deltoid',
    secondaryMuscles: ['anterior deltoid', 'upper trapezius'],
    isCompound: false,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 15,
    description: 'Stand sideways to the anchored end of a landmine, grip the sleeve with both hands and your arm extended, then arc it upward to shoulder height by raising your arm. Lower it back slowly.',
    tips: 'The arc path mirrors the natural movement of the shoulder joint and tends to be more comfortable than dumbbell raises.'
  },
  {
    name: 'Low Cable Row',
    category: 'back',
    equipment: 'cable',
    muscleGroup: 'rhomboids',
    secondaryMuscles: ['latissimus dorsi', 'biceps', 'rear deltoid'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Sit at a low cable station, grip the handle with a neutral grip, and row it toward your lower abdomen while maintaining an upright torso. Extend your arms fully between reps for a full stretch.',
    tips: 'Pause at full contraction and squeeze the shoulder blades together before extending back to start.'
  },
  {
    name: 'Incline Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    muscleGroup: 'rhomboids',
    secondaryMuscles: ['latissimus dorsi', 'rear deltoid', 'biceps'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Lie face down on a bench set to 30-45 degrees incline, hold a dumbbell in each hand with arms hanging straight down, then row them toward your hips by driving your elbows back and up.',
    tips: 'The prone position eliminates lower back stress and allows you to focus entirely on the back muscles.'
  },
  {
    name: 'Wide-Grip Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    muscleGroup: 'latissimus dorsi',
    secondaryMuscles: ['biceps', 'rear deltoid', 'teres major'],
    isCompound: true,
    defaultSets: 3,
    defaultRepRangeLow: 10,
    defaultRepRangeHigh: 12,
    description: 'Grip the pulldown bar wider than shoulder width with an overhand grip, then pull the bar down to your upper chest by driving your elbows down and back. Return slowly to the starting position.',
    tips: 'Lean back slightly and drive the elbows toward the floor to maximize the lat stretch and contraction.'
  }
];
